### ISSUE TITLE
Version 1.0 Feature List & RFC

### ISSUE THREAD

**Issue by psionic-k** [positron-solutions/dslide#20]
This is a list of issues I consider necessary to bring dslide into a mature enough form to consider the architecture and user options stabilized.

- [ ] #19 on-demand action instantiation and element-by-element cooperative ordering of steps between different actions
- [x] #18 macro action for encoding and playing back Emacs macros
- [x] #17 babel markup simplification and more support for normal babel parameters
- [ ] #16 image markup simplification
- [ ] #5 explicit connections between buffers to support better using buffers in actions
- [ ] #21 do "something else" sometimes, overloading `dslide-deck-start` at certain points

Comment on this issue or individually.  May we take over projectors and screen shares everywhere.
